/** Russian labels for registry topics (data/sources.yaml). Unknown topics fall back to the raw key. */
export const TOPIC_LABELS: Record<string, string> = {
  customs: "таможня",
  customs_tariff: "таможенный тариф",
  tariff_rates: "ставки пошлин",
  import_procedures: "процедуры ввоза",
  export_procedures: "процедуры вывоза",
  export_controls: "экспортный контроль",
  export_control: "экспортный контроль",
  dual_use: "двойное назначение",
  import_controls: "контроль ввоза",
  sanctions: "санкции",
  trade_remedies: "антидемпинг и защитные меры",
  forced_labour: "принудительный труд",
  carm: "CARM (учёт импортёров)",
  parcels: "посылки",
  de_minimis: "беспошлинный порог",
  gst_hst_import: "GST/HST при ввозе",
  vat_import: "НДС при ввозе",
  gst_import: "GST при ввозе",
  excise: "акцизы",
  business_number: "регистрация бизнеса",
  food_import_requirements: "требования к продуктам питания",
  sps: "санитарные и фитосанитарные меры",
  product_requirements: "требования к товарам",
  product_safety: "безопасность товаров",
  toys: "игрушки",
  cosmetics: "косметика",
  standards: "стандарты",
  conformity: "подтверждение соответствия",
  technical_regulations: "технические регламенты",
  non_tariff_measures: "нетарифные меры",
  laws: "законы",
  trade_policy: "торговая политика",
  trade_agreements: "торговые соглашения",
  export_support: "господдержка экспорта",
  export_insurance: "экспортное страхование",
  market_info: "информация о рынках",
  licensing: "лицензирование",
  free_zones: "свободные зоны",
  rules_of_origin: "правила происхождения",
  additional_tariffs: "дополнительные тарифы",
  trade_stats: "торговая статистика",
  regions: "регионы",
  logistics: "логистика",
  logistics_index: "индексы логистики",
  export_duties: "экспортные пошлины",
  export_quotas: "экспортные квоты",
  vat_refund: "возврат НДС",
  supply: "где купить",
};

export function topicLabel(topic: string): string {
  return TOPIC_LABELS[topic] ?? topic.replace(/_/g, " ");
}
