"""reference — reference data loaded from official databases (no LLM): HS-6 nomenclature.

Sources (all in data/sources.yaml, section `international`):
  - HS-6 English texts: UN Comtrade reference list H6 (comtradeapi.un.org/files/v1/app/reference/H6.json).
  - HS-6 Russian texts: an optional machine-readable EAEU TN VED file (env HS_RU_SOURCE_URL, eaeunion.org) —
    left empty until the founder confirms a stable official download; search then falls back to English texts
    plus the hand-maintained Russian keyword hints in data/hs_synonyms_ru.json.

Output: data/hs6.json  [{"code": "610910", "en": "...", "ru": "..."}], sorted by code.
Rule this module must never break: nomenclature texts come from the official files only — never typed in by hand
or generated by a model. Hints in hs_synonyms_ru.json are search aids, not classification (principle 6).

Run:  python -m pipeline reference --hs6      (network: GitHub Actions, reference-data.yml)
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

from . import fetch

ROOT = Path(__file__).resolve().parent.parent
HS6_FILE = ROOT / "data" / "hs6.json"
H6_URL = "https://comtradeapi.un.org/files/v1/app/reference/H6.json"


def parse_h6(payload: dict | list) -> list[dict]:
    """UN Comtrade H6 reference: {"results": [{"id": "010121", "text": "010121 - Horses; live, pure-bred ...", ...}]}."""
    rows = payload.get("results", payload) if isinstance(payload, dict) else payload
    out: dict[str, str] = {}
    for row in rows:
        code = str(row.get("id", "")).strip()
        if not re.fullmatch(r"\d{6}", code):
            continue
        text = str(row.get("text", "")).strip()
        text = re.sub(rf"^{code}\s*-\s*", "", text)  # "010121 - Horses; ..." -> "Horses; ..."
        if text:
            out[code] = text
    return [{"code": c, "en": t, "ru": ""} for c, t in sorted(out.items())]


def load_hs6_en() -> list[dict]:
    snap = fetch.fetch_url(H6_URL, save=False)
    if snap.http_status != 200:
        raise RuntimeError(f"H6 reference returned HTTP {snap.http_status}")
    return parse_h6(json.loads(snap.text))


def merge_ru(rows: list[dict], ru_by_code: dict[str, str]) -> list[dict]:
    for row in rows:
        row["ru"] = ru_by_code.get(row["code"], row.get("ru", ""))
    return rows


def build_hs6(out: Path = HS6_FILE) -> Path:
    rows = load_hs6_en()
    existing: dict[str, str] = {}
    if out.exists():  # keep Russian texts already present (from a previous official load)
        for r in json.loads(out.read_text(encoding="utf8")):
            if r.get("ru"):
                existing[r["code"]] = r["ru"]
    ru_url = os.environ.get("HS_RU_SOURCE_URL")
    if ru_url:
        snap = fetch.fetch_url(ru_url, save=False)
        existing.update(parse_ru_tnved(snap.text))
    rows = merge_ru(rows, existing)
    out.write_text(json.dumps(rows, ensure_ascii=False, indent=0) + "\n", encoding="utf8")
    print(f"{len(rows)} HS-6 codes -> {out} ({sum(1 for r in rows if r['ru'])} with Russian text)")
    return out


def parse_ru_tnved(text: str) -> dict[str, str]:
    """Best-effort parser for a plain-text/CSV EAEU TN VED export: lines '6109 10 000 0;Футболки...' or '610910;...'."""
    out: dict[str, str] = {}
    for line in text.splitlines():
        m = re.match(r"^\s*(\d{4})\s?(\d{2})[\s\d]*[;,\t]\s*(.+?)\s*$", line)
        if m:
            code = m.group(1) + m.group(2)
            out.setdefault(code, m.group(3).strip('" '))
    return out


def main(argv=None) -> int:
    build_hs6()
    return 0
