"""Scaffold demo pages for every product group in data/corridors.yaml (stage 0, before the pipeline exists).

What it does
  - For each corridor and each product group without a hand-written page, writes
    web/data/pages/<corridor>-<hs6>-ru.json in the PageContent shape.
  - For each export country (CN, RU) and each HS-4 group, writes web/data/supply/<cc>-<hs4>-ru.json.

What it does NOT do — on purpose (CLAUDE.md, principles 1–4)
  - It never invents duty rates, licences, standards, sanctions or programs for a product group.
    Everything that depends on the product is emitted with status "not_found" ("источник не перечитан") and
    the calculator is left empty until the rates layer fills the `rates` table.
  - Country-pair facts (agreements, sanctions regime, export declaration, documents, logistics) are copied
    from the hand-written demo page of the same corridor and stay flagged as demo.

All output is `isDemo: true`. Re-running overwrites generated files only; hand-written pages are left alone
(their `_handwritten` marker is absent, so we detect them by the GENERATED marker instead).

Usage:  python scripts/scaffold_demo_pages.py
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PAGES = ROOT / "web" / "data" / "pages"
SUPPLY = ROOT / "web" / "data" / "supply"
GENERATED = "generated by scripts/scaffold_demo_pages.py"

TEMPLATE_PAGE = {"cn-ca": "cn-ca-610910-ru.json", "ru-ir": "ru-ir-100199-ru.json"}
TEMPLATE_SUPPLY = {"CN": "cn-8432-ru.json", "TR": "tr-6109-ru.json"}

NOT_FOUND = {"status": "none", "source": "источник не перечитан", "label": "не собрано — статус not_found"}
BROKER = {"status": "note", "source": "подтвердите у брокера", "label": "страница работает на уровне группы HS-6"}
NOT_LOADED = {"status": "none", "source": "таблица rates", "label": "ставка не загружена"}

# Words that mark a template line as product-specific (wheat / grain / cotton T-shirts) — such lines are never reused.
PRODUCT_WORDS = ("пшениц", "зерн", "хлопк", "футболк", "одежд", "трикотаж", "продовольств", "сельскохоз", "апк", "6109", "1001", "фитосанитар", "лиценз", "перечн", "ставка", "пошлин", "квот", "текстил", "воспламеня")

LOC = {"CN": "в Китае", "CA": "в Канаде", "RU": "в России", "IR": "в Иране", "TR": "в Турции"}


def generic(facts: list[dict]) -> list[dict]:
    """Keeps only lines that do not mention the template product."""
    return [f for f in facts if not any(w in str(f["text"]).lower() for w in PRODUCT_WORDS)]

# Accusative forms where the nominative from corridors.yaml does not work after "Везу …".
ACCUSATIVE = {
    "Кукуруза": "кукурузу",
    "Чечевица": "чечевицу",
    "Бумага офисная": "бумагу офисную",
    "Косметика для ухода за кожей": "косметику для ухода за кожей",
    "Пшеница продовольственная": "пшеницу продовольственную",
    "Кухонная утварь из нержавеющей стали": "кухонную утварь из нержавеющей стали",
}


def accusative(name: str) -> str:
    return ACCUSATIVE.get(name, name[0].lower() + name[1:])


def hs_label(hs6: str) -> str:
    return f"HS {hs6[:4]}.{hs6[4:]}"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf8"))


def is_generated(path: Path) -> bool:
    return path.exists() and GENERATED in path.read_text(encoding="utf8")


def product_specific_summary(country_to: str, prod: str) -> list[dict]:
    return [
        {"key": "Пошлина при ввозе", "text": "Ставка для этой группы не загружена: слой ставок ещё не заполнил таблицу rates", "stamp": NOT_LOADED},
        {"key": "Лицензия на экспорт", "text": "Требуется ли лицензия для этой группы — источник не перечитан", "stamp": NOT_FOUND},
        {"key": "Разрешения и стандарты", "text": f"Требования при ввозе {country_to} к этой группе не собраны", "stamp": NOT_FOUND},
        {"key": "Санкции по товару", "text": "Товарная группа по санкционным перечням не проверена", "stamp": NOT_FOUND},
    ]


def scaffold_page(tpl: dict, corridor: dict, group: dict) -> dict:
    hs6 = str(group["hs6"])
    prod = accusative(group["name_ru"])
    page = copy.deepcopy(tpl)
    page["_generated"] = GENERATED
    page["product"] = {"hs6": hs6, "name": prod, "hsLabel": hs_label(hs6)}
    page["isDemo"] = True
    fr, to = page["corridor"]["from"], page["corridor"]["to"]
    fr.setdefault("loc", LOC.get(fr["code"], fr["name"]))
    to.setdefault("loc", LOC.get(to["code"], to["name"]))
    page["corridor"]["modes"] = list(corridor.get("modes", ["b2b"]))
    if "parcel" not in page["corridor"]["modes"]:
        page["corridor"]["parcelDisabledReason"] = "Режим посылок для этого коридора не открыт"

    page["status"] = {
        "sourcesTotal": 0,
        "sourcesMissing": 0,
        "lastChecked": "",
        "text": (
            f"Страница-заготовка для группы {hs_label(hs6)}: конвейер ещё не перечитывал источники. "
            f"Строки о паре стран взяты из демо коридора {fr['name']} → {to['name']}; всё, что зависит от товара, "
            "помечено «не собрано». Это не юридическая консультация."
        ),
    }

    # Summary: country-pair lines that do not depend on the product + honest gaps for the product.
    keep_keys = {"Соглашение", "Налог на границе"}
    pair_lines = generic([f for f in tpl["summary"]["facts"] if f.get("key") in keep_keys])
    page["summary"]["facts"] = product_specific_summary(to["to"], prod) + pair_lines

    if "sanctions" in page:
        page["sanctions"]["text"] = (
            f"{fr['name']} и {to['name']} — под санкциями Канады, США, ЕС и Великобритании. "
            f"Статус группы {hs_label(hs6)} по санкционным перечням не проверен: до сборки страницы считайте, что "
            "ограничения возможны. Расчёты через банки этих стран невозможны, контрагента нужно проверить по спискам. "
            "Страница показывает ограничения как есть и не подсказывает, как их обойти."
        )

    page["rating"].update({
        "lead": "Оценка появится после сборки страницы конвейером. Балл без основания не показывается.",
        "total": 0,
        "verdict": "оценка не собрана",
        "verdictStatus": "warn",
        "parts": [{"name": p["name"], "score": None, "basis": "не собрано"} for p in tpl["rating"]["parts"]],
    })
    page["verdict"] = {
        "prosTitle": "Выгодно",
        "consTitle": "Мешает",
        "pros": [{"kind": "pro-check", "text": "Появится после сборки: выгоды считаются по правилам из источников."}],
        "cons": [{"kind": "con", "text": "Появится после сборки: препятствия считаются по правилам из источников."}],
    }
    page["compare"] = {
        "id": "sw",
        "title": f"Куда ещё везти {prod} {fr['from']}",
        "lead": "Индексный слой для этой группы не собран.",
        "rows": [],
    }

    # Regime: keep pair-level lines (agreement, certificate, listed-persons rule); product-level checks are not_found.
    page["regime"]["facts"] = generic(tpl["regime"]["facts"]) + [
        {"text": "Защитные меры (антидемпинг, компенсационные пошлины) по этой группе: не проверено.", "stamp": NOT_FOUND},
        {"text": "Санкционные режимы Канады, США, ЕС и Великобритании по этой группе: не проверено.", "stamp": NOT_FOUND},
    ]

    # Export: keep country-level facts (declaration, VAT, certificate) — product-specific ones become not_found.
    page["export"]["facts"] = [
        {"text": "Экспортная лицензия: требуется ли для этой группы — источник не перечитан.", "stamp": NOT_FOUND},
        {"text": "Экспортная пошлина или квота для этой группы: не собрано.", "stamp": NOT_LOADED},
    ] + generic(tpl["export"]["facts"])
    page["export"]["groups"] = [
        {"title": g["title"], "facts": generic(g["facts"]) + [{"text": "Программы поддержки для этой группы: не проверено.", "stamp": NOT_FOUND}]}
        for g in tpl["export"].get("groups", [])
    ]

    page["import"]["facts"] = [
        {"text": f"Код товара: {hs_label(hs6)} — {group['name_ru'].lower()}. Национальный код и ставку подтверждают брокер или предварительное решение таможни.", "stamp": BROKER},
        {"text": "Пошлина при ввозе: базовая и преференциальная ставки не загружены — заполняется из таблицы rates.", "stamp": NOT_LOADED},
        {"text": "Налоги на границе для этой группы: не проверено.", "stamp": NOT_FOUND},
        {"text": "Разрешения, стандарты, маркировка для этой группы: не собрано.", "stamp": NOT_FOUND},
    ]

    page["cost"] = {
        "id": "s4",
        "number": 4,
        "title": tpl["cost"]["title"],
        "lead": "Калькулятор появится, когда слой ставок загрузит ставки для этой группы.",
        "currency": tpl["cost"]["currency"],
        "inputs": [],
        "lines": [],
        "totalLabel": tpl["cost"]["totalLabel"],
        "note": "Ставки для этой группы не загружены. Конвейер никогда не подставляет числа по памяти.",
    }

    page["logistics"]["facts"] = [
        {"text": "Маршруты, сроки и ориентир стоимости для этой группы не собраны.", "stamp": NOT_FOUND},
    ]

    # Documents: keep the export-country list; the import-country list depends on the product.
    docs = [
        {"title": g["title"], "items": [i for i in g["items"] if not any(w in i.lower() for w in PRODUCT_WORDS)]}
        for g in tpl["documents"]["groups"] if g["title"].startswith("На вывоз")
    ]
    docs.append({"title": f"На ввоз {to['to']}", "items": ["Список для этой группы появится после сборки"]})
    page["documents"]["groups"] = docs

    page["sources"]["lead"] = "Источники для этой группы ещё не перечитывались. Ниже — источники демо коридора, на которые опираются строки о паре стран."
    page["sources"]["rows"] = [r for r in tpl["sources"]["rows"] if not any(w in r["confirms"].lower() for w in PRODUCT_WORDS)]
    page["rail"]["followSample"] = None
    return page


def scaffold_supply(tpl: dict, country: dict, hs4: str, name: str, corridor_id: str, hs6s: list[str]) -> dict:
    page = copy.deepcopy(tpl)
    page["_generated"] = GENERATED
    page["country"] = {**country, "loc": country.get("loc") or LOC.get(country["code"], country["name"])}
    page["product"] = {"hs": hs4, "name": accusative(name), "hsLabel": f"HS {hs4}"}
    page["isDemo"] = True
    loc = country.get("loc") or country["name"]
    page["status"] = {
        "sourcesTotal": 0,
        "sourcesMissing": 0,
        "lastChecked": "",
        "text": f"Страница-заготовка слоя «Где купить» для группы HS {hs4} {loc}: регионы и показатели не собраны, источники не перечитывались. Не рекомендация поставщиков.",
    }
    page["summary"]["facts"] = [
        {"key": "Главные регионы", "text": "Регионы производства этой группы не собраны", "stamp": NOT_FOUND},
        {"key": "Показатели", "text": "Заполняются из региональной статистики; не загружено", "stamp": {"status": "none", "source": "статистика", "label": "не загружено"}},
        {"key": "Где искать", "text": "Официальные реестры и выставки — строки уровня страны ниже", "stamp": {"status": "note", "source": "уровень страны", "label": "см. раздел 2"}},
    ]
    page["regions"]["lead"] = "Регионы для этой группы появятся после сборки из статистики выпуска и реестров кластеров."
    page["regions"]["rows"] = [
        {"region": "—", "note": "Регионы не собраны", "indicator": "не загружено", "stamp": NOT_FOUND},
    ]
    page["check"]["facts"] = [
        {"text": "Требуется ли экспортная лицензия для этой группы — источник не перечитан.", "stamp": NOT_FOUND},
        {"text": "Код товара уточняйте у брокера или по предварительному решению таможни: страница работает на уровне группы HS-4/HS-6.", "stamp": BROKER},
    ]
    page["corridors"]["links"] = [
        {"label": f"{country['name']} → страница коридора, {hs_label(h)}", "href": f"/corridor/{corridor_id}/{h}", "state": "open"}
        for h in hs6s
    ]
    page["sources"]["lead"] = "Источники для этой группы ещё не перечитывались; ниже — источники уровня страны."
    return page


def main() -> None:
    corridors = yaml.safe_load((ROOT / "data" / "corridors.yaml").read_text(encoding="utf8"))["corridors"]
    written = 0
    ru_supply_tpl = None

    for corridor in corridors:
        tpl = load(PAGES / TEMPLATE_PAGE[corridor["id"]])
        for group in corridor["product_groups"]:
            hs6 = str(group["hs6"])
            out = PAGES / f"{corridor['id']}-{hs6}-ru.json"
            if out.exists() and not is_generated(out):
                continue  # hand-written page
            out.write_text(json.dumps(scaffold_page(tpl, corridor, group), ensure_ascii=False, indent=2) + "\n", encoding="utf8")
            written += 1

        # Supply pages for the export country, one per HS-4.
        cc = corridor["from"].upper()
        country = tpl["corridor"]["from"]
        if cc in TEMPLATE_SUPPLY:
            stpl = load(SUPPLY / TEMPLATE_SUPPLY[cc])
        else:
            # RU: derive a country-level template from the CN one, replacing the "find" facts with RU agencies.
            stpl = load(SUPPLY / TEMPLATE_SUPPLY["CN"])
            stpl["find"]["facts"] = [
                {"text": "Региональная статистика выпуска и отгрузки по субъектам публикует Росстат — основа для списка регионов.", "stamp": {"status": "warn", "source": "rosstat.gov.ru", "label": "демо — требует проверки по источнику"}},
                {"text": "Реестры промышленных кластеров и особых экономических зон ведёт Минпромторг; по ним видно профиль региона.", "stamp": {"status": "warn", "source": "minpromtorg.gov.ru", "label": "демо — требует проверки по источнику"}},
                {"text": "Российский экспортный центр — государственный институт поддержки экспорта; точка входа для запроса по отрасли.", "stamp": {"status": "warn", "source": "exportcenter.ru", "label": "демо — требует проверки по источнику"}},
            ]
            stpl["sources"]["rows"] = [
                {"source": "rosstat.gov.ru", "confirms": "выпуск по регионам", "checked": "—", "status": {"text": "не перечитан", "kind": "warn"}},
                {"source": "minpromtorg.gov.ru", "confirms": "кластеры, ОЭЗ, программы", "checked": "—", "status": {"text": "не перечитан", "kind": "warn"}},
                {"source": "exportcenter.ru", "confirms": "поддержка экспортёров", "checked": "—", "status": {"text": "не перечитан", "kind": "warn"}},
            ]
            ru_supply_tpl = stpl
        stpl["corridors"]["title"] = f"Куда везти {country['from']}"
        stpl["corridors"]["lead"] = "Страницы коридоров вывоза этой группы."

        by_hs4: dict[str, tuple[str, list[str]]] = {}
        for group in corridor["product_groups"]:
            hs6 = str(group["hs6"])
            name, hs6s = by_hs4.setdefault(hs6[:4], (group["name_ru"], []))
            hs6s.append(hs6)
        for hs4, (name, hs6s) in by_hs4.items():
            out = SUPPLY / f"{cc.lower()}-{hs4}-ru.json"
            if out.exists() and not is_generated(out):
                continue
            out.write_text(json.dumps(scaffold_supply(stpl, country, hs4, name, corridor["id"], hs6s), ensure_ascii=False, indent=2) + "\n", encoding="utf8")
            written += 1

    print(f"written {written} generated files; hand-written pages untouched")


if __name__ == "__main__":
    main()
